name: Build Android (Buildozer Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    timeout-minutes: 180

    steps:
    - uses: actions/checkout@v4

    # Vérifier la version de Buildozer et tar
    - name: Vérifier Buildozer et tar
      run: |
        buildozer --version
        tar --version

    # Construire l’APK debug
    - name: Build APK (debug)
      run: |
        buildozer -v android debug
